[project]
name = "Crawler"
version = "0.1.0"
description = "主流媒体平台爬虫"
authors = [
    {name = "", email = ""},
]
dependencies = [
    "beautifulsoup4==4.12.3",
    "blinker==1.8.2",
    "bs4==0.0.2",
    "certifi==2024.2.2",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "decorator==4.4.2",
    "Flask==3.0.3",
    "gunicorn==22.0.0",
    "idna==3.7",
    "imageio==2.34.1",
    "imageio-ffmpeg==0.4.9",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.4",
    "MarkupSafe==2.1.5",
    "moviepy==1.0.3",
    "numpy==1.26.4",
    "packaging==24.0",
    "pillow==10.3.0",
    "proglog==0.1.10",
    "PyExecJS==1.5.1",
    "PyYAML==6.0.1",
    "requests==2.32.3",
    "setuptools==70.0.0",
    "six==1.16.0",
    "soupsieve==2.5",
    "SQLAlchemy==2.0.30",
    "tqdm==4.66.4",
    "typing-extensions==4.12.0",
    "urllib3==2.2.1",
    "Werkzeug==3.0.3",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
